# Generated by Django 4.2.3 on 2023-07-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpackage',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='exam.mastertimeline'),
        ),
    ]
