# Generated by Django 4.2.3 on 2023-08-06 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_mastersection_mastersubtest_masterquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactUserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userpackage_related', to='exam.masterpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpackage_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
