# Generated by Django 4.2.3 on 2023-08-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0007_transactuserpackage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteranswer',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='masterquestion',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transactuserpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_related', to='exam.masterpackage'),
        ),
        migrations.AlterField(
            model_name='transactuserpackage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
