# Generated by Django 4.2.3 on 2023-08-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_masteranswer_name_alter_masterquestion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteranswer',
            name='isright',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
