# Generated by Django 4.2.3 on 2023-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_masterquestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersubtest',
            name='duration',
            field=models.IntegerField(default=1260),
            preserve_default=False,
        ),
    ]
