# Generated by Django 4.2.3 on 2023-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_mastersubtest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterquestion',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
