# Generated by Django 4.2.3 on 2023-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_masterquestion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteranswer',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
