# Generated by Django 4.2.3 on 2023-08-25 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0013_masteranswer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactuserpackage',
            name='sectiondone',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TransactUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_transact_related', to='exam.masteranswer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_transact_related', to='exam.masterpackage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_transact_related', to='exam.masterquestion')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_transact_related', to='exam.mastersection')),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtest_transact_related', to='exam.mastersubtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transact_related', to=settings.AUTH_USER_MODEL)),
                ('userpackage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userpackage_related', to='exam.transactuserpackage')),
            ],
        ),
    ]
