# Generated by Django 4.2.3 on 2023-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_transactuserpackage_sectiondone_transactuseranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactuseranswer',
            name='isselected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
