# Generated by Django 4.2.3 on 2023-09-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_transactuseranswer_isselected'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateLoaderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipackage', models.CharField(max_length=100)),
                ('isection', models.CharField(max_length=100)),
                ('isubtest', models.CharField(max_length=100)),
                ('iquestionnumber', models.CharField(max_length=100)),
                ('iquestiontype', models.CharField(max_length=100)),
                ('iquestiondescription', models.TextField()),
                ('ianswer1', models.TextField()),
                ('ianswer2', models.TextField()),
                ('ianswer3', models.TextField()),
                ('ianswer4', models.TextField()),
                ('ianswer5', models.TextField()),
                ('ianswer6', models.TextField()),
                ('ianswer7', models.TextField()),
                ('ianswer8', models.TextField()),
                ('ianswer9', models.TextField()),
                ('ianswer10', models.TextField()),
            ],
        ),
    ]
