# Generated by Django 4.2.3 on 2023-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='minimumvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='university',
            name='province',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
