# Generated by Django 4.2.3 on 2023-08-31 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')])),
                ('phonenumber', models.CharField(max_length=100)),
                ('instagramaccount', models.CharField(max_length=100)),
                ('instagramfollower', models.IntegerField()),
                ('schoolname', models.CharField(max_length=200)),
                ('schoolgrade', models.IntegerField(choices=[(1, '1 SMA'), (2, '2 SMA'), (3, '3 SMA'), (4, 'Alumni')])),
                ('schoolprogram', models.IntegerField(choices=[(1, 'Ilmu Pengetahuan Alam'), (2, 'Ilmu Pengetahuan Sosial'), (3, 'Bahasa'), (4, 'Agama'), (5, 'Teknik'), (6, 'Non Teknik')])),
                ('schoolfinishyear', models.CharField(max_length=10)),
                ('studentnumber', models.CharField(max_length=200)),
                ('studyprogram1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studyprogram1_related', to='ref.studyprogram')),
                ('studyprogram2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studyprogram2_related', to='ref.studyprogram')),
                ('university1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='university1_related', to='ref.university')),
                ('university2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='university2_related', to='ref.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
