# Generated by Django 4.2.3 on 2023-09-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
        ('useraccount', '0003_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagramaccount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagramfollower',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='schoolfinishyear',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='schoolgrade',
            field=models.IntegerField(choices=[(1, '1 SMA'), (2, '2 SMA'), (3, '3 SMA'), (4, 'Alumni')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='schoolname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='schoolprogram',
            field=models.IntegerField(choices=[(1, 'Ilmu Pengetahuan Alam'), (2, 'Ilmu Pengetahuan Sosial'), (3, 'Bahasa'), (4, 'Agama'), (5, 'Teknik'), (6, 'Non Teknik')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studentnumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studyprogram1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studyprogram1_related', to='ref.studyprogram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studyprogram2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studyprogram2_related', to='ref.studyprogram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university1_related', to='ref.university'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university2_related', to='ref.university'),
        ),
    ]
