# Generated by Django 4.2.3 on 2023-09-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_userprofile_birthdate_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStudentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentnumber', models.CharField(max_length=200)),
                ('studentname', models.CharField(max_length=200)),
                ('studentbranch', models.CharField(max_length=200)),
                ('studenttimeline', models.IntegerField()),
            ],
        ),
    ]
